
#Update a puzzle
PATCH http://localhost:3000/puzzles/1
Content-Type: application/json
{
  "id": ,
  "title": "",
  "description": "",
  "difficulty": "",
  "points": "",
  "metadata": "",
  "steps": "", 
  
}