#Create an achievement 
POST http://localhost:3000/achievements
Content-Type: application/json

  {
    "id": " ",
    "user": " ",
    "type": "", 
    "title": "",
    "description": "",
    "nftTokenId": "",
    "unlockedAt": " "

  }