#Update a specific user

PATCH http://localhost:3000/users/1
Content-Type: application:json 

  {
    "id": ,
    "username": "",
    "email": "",
    "password":"",
    "walletAddress": "",
    "createdAt": "" ,
    "updatedAt": ""
  }