#Create a user 

POST http://localhost:3000/users 
Content-Type: application:json

  {
    "id": ,
    "username": "",
    "email": "",
    "password":"",
    "walletAddress": "",
    "createdAt": "" ,
    "updatedAt": ""
  }